version: "3.7"

services:
  db-service:
    image: postgres:latest
    restart: always
    networks:
      - webapp-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '654321'
  
  # test
  adminer:
    image: adminer
    restart: always
    networks:
      - webapp-network
    ports:
      - 8080:8080

  api-service:
    build: ./api
    container_name: api-service
    restart: always
    networks:
      - webapp-network
    environment:
      - APP_NAME=api-serivce
      - DEV=False
      - DEBUG=False
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:654321@db-service/postgres
      # use container inner port
      # https://stackoverflow.com/questions/55523273/why-container-cant-request-to-another
      # - MEDIA_SERVICE_RESTFUL_API_URL=http://media-service:80/index/api
    ports:
      - 5678:5678
    networks:
      - webapp-network
    depends_on:
      - db-service

  webapp-service:
    build: ./webapp
    container_name: web-service
    restart: always
    ports:
      - 8881:80
    networks:
      - webapp-network
    depends_on:
      - api-service
    
    # media-service:
  #   image: panjjo/zlmediakit
  #   container_name: media-service
  #   restart: always
  #   ports:
  #     - 1935:1935 
  #     - 8080:80 
  #     - 8554:554 
  #     - 10000:10000 
  #     - 10000:10000/udp
networks:
  webapp-network: